### ISSUE TITLE
GitHub rate limit reached: reduce number of API calls

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/github-maintainer-cli#2]
Arbitrary rate limits are reached easily, reduce number of API calls to work around...

**Comment by prayerslayer** [comment]
Or maybe add the possibility to use a token?

On 7 December 2015 at 22:47, Henning Jacobs notifications@github.com
wrote:

> Arbitrary rate limits are reached easily, reduce number of API calls to
> work around...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zalando-stups/github-maintainer-cli/issues/2.

## 

undefined = () => {}

(o_
//\

V_/_  Nikolaus Piccolotto
      engineer.js

**Comment by hjacobs** [comment]
@prayerslayer hmm, what do you mean? It's already using a personal access token.

**Comment by prayerslayer** [comment]
Ah, ok, didn't look at the code. So you get rate-limited even with a token?
:scream:

On 8 December 2015 at 10:55, Henning Jacobs notifications@github.com
wrote:

> @prayerslayer https://github.com/prayerslayer hmm, what do you mean?
> It's already using a personal access token.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zalando-stups/github-maintainer-cli/issues/2#issuecomment-162835202
> .

## 

undefined = () => {}

(o_
//\

V_/_  Nikolaus Piccolotto
      engineer.js

**Comment by lasomethingsomething** [comment]
Hi @hjacobs @prayerslayer, can we close this issue? It dates back to Dec 2015.
