### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/github-maintainer-cli#3]
```
    ImportError: No module named 'setuptools'
```

Freshly installed Ubuntu 16.04 with python3-pip module:

```
$ sudo apt-get install python3-pip
$ pip3 install -U github-maintainer
....
    ImportError: No module named 'setuptools'
```

**Comment by hjacobs** [comment]
@sarnowski I guess you will have the same problem with all other STUPS CLI tools?

**Comment by lasomethingsomething** [comment]
@hjacobs Hey, can we close this issue? It dates back to April 2016. 

Or, we could add a "Help Wanted" label.
