### ISSUE TITLE
What's the future of this project?

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando-stups/github-maintainer-cli#4]
Hey, is there a reason why it's on stups and not main org? Also, do you plan on continuing work, or should we actually store it on the incubator for now?

**Comment by hjacobs** [comment]
It currently works for me (to see open PRs for projects I'm the maintainer of), we could extend the feature list to make it more useful. I will move it to the main repository as it is not related to STUPS.

**Comment by lasomethingsomething** [comment]
+1 for moving it to the main org. Do you think this could be something we could also pitch to GitHub? Eric B, Lothar and I met with them this week to propose a bunch of feature requests and tweaks to their various products. The purpose of this project is likely to resonate with lots of devs.

**Comment by lasomethingsomething** [comment]
@hjacobs following up on conversation above :)

**Comment by hjacobs** [comment]
@LappleApple already in the main org: https://github.com/zalando/github-maintainer-cli
